# Generated by Django 5.0.6 on 2024-05-23 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="task",
        ),
    ]
