# Generated by Django 5.0.6 on 2024-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_task_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="option1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="option2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="option3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="option4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="option5",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
