# Generated by Django 5.0.6 on 2024-05-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0005_task_option1_task_option2_task_option3_task_option4_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="courses.course",
            ),
        ),
    ]
