# Generated by Django 5.0.6 on 2024-05-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_step_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="courses.course",
            ),
        ),
    ]
