# Generated by Django 5.0.6 on 2024-05-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_step_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="courses.step",
            ),
        ),
    ]
